Update actualizar_token.yml

diff --git a/.github/workflows/actualizar_token.yml b/.github/workflows/actualizar_token.yml
--- a/.github/workflows/actualizar_token.yml
+++ b/.github/workflows/actualizar_token.yml
@@ -18,9 +18,17 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Extraer Token de la Web
+      env:
+        PAGINA_SECRETA: ${{ secrets.URL_EXTRACCION }}
       run: |
-        # Descargar el HTML de la página web
-        curl -s https://jimsa.alwaysdata.net/fl_tok/ > pagina.html
+        # Validar primero si el Secret está configurado en el repositorio
+        if [ -z "$PAGINA_SECRETA" ]; then
+          echo "Error: El Secreto 'URL_EXTRACCION' no está configurado en GitHub."
+          exit 1
+        fi
+
+        # Descargar el HTML usando la variable oculta
+        curl -s "$PAGINA_SECRETA" > pagina.html
         
         # Extraer la URL del token buscando la cadena que empieza con 'https://edge-' hasta el final de la línea
         URL_TOKEN=$(grep -oE "https://edge-[^<\"]+" pagina.html | head -n 1)
@@ -34,7 +42,7 @@ jobs:
           exit 1
         fi
         
-        echo "Token extraído con éxito: $URL_TOKEN"
+        echo "Token extraído con éxito."
         
         # Guardar temporalmente en el entorno de ejecución de GitHub
         echo "NEW_TOKEN=$URL_TOKEN" >> $GITHUB_ENV
